name: Node.js CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run lint
    - run: npm run test
    - name: Deploy and wait
      uses: ashishkujoy/render-ci-deploy@v1.0.1
      with:
        service-id: ${{ secrets.SERVICE_ID }}
        service-key: ${{ secrets.SERVICE_KEY }}
        api-key: ${{ secrets.API_KEY }}
        max-deployment-wait-ms: 360000
        delay-in-ms: 10000
